import Head from "next/head";
import Herosection from "../components/sections/Herosection";
import Logosection from "../components/sections/Logosection";
import NFTSection from "../components/sections/NFTSection";

export default function Home() {
  return (
    <div>
      <Head>
        <title>NFT Website | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Herosection />
      <Logosection />
      <NFTSection />
    </div>
  );
}
